### ISSUE TITLE
RunInfo regex needs to cater for modified run info xml files

### ISSUE THREAD

**Issue by alexiswl** [umccr/cttso-ica-to-pieriandx#210]

**Comment by victorskl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Service: Reprocess 240220_A01052_0183_BH5HLHDSXC TSO_ctDNA pipeline](https://trello.com/c/mhZQMaSZ/1615-service-reprocess-240220a010520183bh5hlhdsxc-tsoctdna-pipeline)

**Comment by victorskl** [comment]
This is issue ticket. See left hand side panel > Development section > related PRs for the actual code changes that fix the issue. FYI
