### ISSUE TITLE
SBJ03366_L2300790 failed

### ISSUE THREAD

**Issue by pdiakumis** [umccr/cttso-ica-to-pieriandx#97]
Slack: https://umccr.slack.com/archives/C8CG6K76W/p1688192222630239

CloudWatch [link](https://ap-southeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-2#logsV2:log-groups/log-group/$252Faws$252Fbatch$252Fcttso-ica-to-pieriandx/log-events/cttso-ica-to-pieriandx$252Fdefault$252Fb4959f25cf2d4d62b5dd3ef24646e459)

**Comment by alexiswl** [comment]
Has been successfully submitted to PierianDx

https://umccr.slack.com/archives/C8CG6K76W/p1688346417735159
